import { getCreds } from "./lib/creds";

export interface Job {
  id: number;
  created_ms: number;
  started_ms: number | null;
  finished_ms: number | null;
  status: string;
  phase: string | null;
  exit_code: number | null;
  ram_peak: number;
  disk_peak: number;
  reaped_ms: number | null;
  summary: string | null;
  // Per-model summaries (see src/summarize.rs): reproducer one-liner (start), result
  // one-liner (end), two-paragraph "why it failed" detail (end).
  repro_summary: string | null;
  result_summary: string | null;
  detail: string | null;
  // Provenance for jobs created from an external source (LKML candidate); null otherwise.
  source_url: string | null;
  title: string | null;
  // Terse two-word title generated by the summarizer, shown inline after #id.
  short_title: string | null;
  // Per-summary generation metadata as raw JSON: {field:{ms,tokens,model}}. Drives the
  // hover tooltip. NULL until the first summary lands.
  summary_meta: string | null;
  // The job's origin ("scaffold" for scaffold jobs, "lkml" for candidate runs, else null).
  // Scaffold jobs get an extra "scaffold" phase step (see lib/format phaseList).
  source: string | null;
}
export interface SummarizerInfo {
  loaded: boolean;
  label: string;
  mem_bytes: number;
  // The configured summary backends; one is primary (its output is shown by default).
  servers?: { label: string; model: string; primary: boolean }[];
}
// One backend's summary for a job field (every backend's output, behind the
// "see all models" expander). The default view uses the per-field columns on Job.
export interface JobSummary {
  field: string;   // "title" | "repro" | "result" | "detail"
  server: string;  // backend label
  text: string;
  ms: number | null;
  tokens: number | null;
  model: string | null;
}
export interface Sample { ts_ms: number; rss_bytes: number; disk_bytes: number; }
export interface Peak { id: number; ram_peak: number; disk_peak: number; status: string; }
// A reproducer cover letter found on LKML, runnable with one click.
export interface Candidate {
  msgid: string;
  list: string | null;
  title: string | null;
  source_url: string;
  detected_ms: number;
  job_id: number | null;
}

const TOKEN_KEY = "mk_token";
export function token(): string {
  return localStorage.getItem(TOKEN_KEY) || "";
}
export function hasToken(): boolean {
  return token().length > 0;
}
export function setToken(t: string) {
  localStorage.setItem(TOKEN_KEY, t.trim());
}
export function clearToken() {
  localStorage.removeItem(TOKEN_KEY);
}

// A direct link can carry the bearer in the URL fragment as #rev=<commit>, so shared
// links unlock without the password prompt (the server now accepts a >=8-char prefix
// of the v7.1 commit). The fragment is never sent to the server. Runs at module load,
// before App reads hasToken(); clear the hash afterward so the secret doesn't linger
// in the address bar or get copied out of it.
const rev = new URLSearchParams(location.hash.slice(1)).get("rev");
if (rev) {
  setToken(rev);
  history.replaceState(null, "", location.pathname + location.search);
}
function headers(): HeadersInit {
  const t = token();
  return t ? { Authorization: `Bearer ${t}` } : {};
}

// Wrap fetch so a rejected token (401) drops the stored token and tells the app to
// re-prompt for the v7.1 commit, instead of silently retrying with a bad token.
async function authed(input: string, init?: RequestInit): Promise<Response> {
  const r = await fetch(input, { ...init, headers: { ...headers(), ...(init?.headers || {}) } });
  if (r.status === 401) {
    clearToken();
    window.dispatchEvent(new Event("mk-unauthorized"));
    throw new Error("unauthorized");
  }
  return r;
}

export async function listJobs(): Promise<Job[]> {
  return (await authed("/api/jobs")).json();
}
export async function getJob(id: number): Promise<Job> {
  return (await authed(`/api/jobs/${id}`)).json();
}
export async function getJobSummaries(id: number): Promise<JobSummary[]> {
  return (await authed(`/api/jobs/${id}/summaries`)).json();
}
export async function submit(bundle: string): Promise<{ id: number }> {
  return (await authed("/api/jobs", { method: "POST", body: bundle })).json();
}
export async function listCandidates(): Promise<Candidate[]> {
  return (await authed("/api/candidates")).json();
}
export async function runCandidate(msgid: string): Promise<{ id: number }> {
  return (await authed(`/api/candidates/${encodeURIComponent(msgid)}/run`, { method: "POST" })).json();
}
// A patch-series cover letter (or standalone patch) on a lore list, from the on-demand
// LKML browser. `body` is the cover-letter text — the reproducer-to-be.
export interface LkmlPatch { title: string; url: string; body: string; }
// One page of cover letters from a list's git mirror. `more` => another page exists;
// `next` is the skip to pass to fetch it.
export interface LkmlPage { patches: LkmlPatch[]; more: boolean; next: number; }
export async function listLkmlPatches(list: string, skip = 0): Promise<LkmlPage> {
  return (await authed(`/api/lkml/patches?list=${encodeURIComponent(list)}&skip=${skip}`)).json();
}
// "Scaffold a reproducer": create a background JOB whose first stage runs the opencode
// agent to write a bundle from a patch series, then runs it. Returns the new job id (open
// it like any job). Auto-fills the OpenAI creds from settings; the backend requires them
// (no free tier) and rejects with 400 if any is missing.
export async function startScaffold(req: { thread?: string; patch?: string; commit?: string; note?: string }): Promise<{ id: number }> {
  return (await authed("/api/scaffold", {
    method: "POST", headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ ...req, ...getCreds() }),
  })).json();
}
// "Refine from text": send an edited reproducer bundle (plus an optional prompt) to the
// agent to improve it — no parent job, no run logs. Returns the new (scaffold) job id.
export async function refineText(bundle: string, note?: string): Promise<{ id: number }> {
  return (await authed("/api/scaffold/refine-text", {
    method: "POST", headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ bundle, note, ...getCreds() }),
  })).json();
}
// "Refine" a job: create a new scaffold job that hands this job's reproducer + all its
// run logs back to the opencode agent to fix ("this failed, fix it"), then runs the
// corrected bundle. Returns the new (child) job id. Needs the same OpenAI creds as scaffold.
export async function refineJob(id: number, note?: string): Promise<{ id: number }> {
  return (await authed(`/api/jobs/${id}/refine`, {
    method: "POST", headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ ...getCreds(), note }),
  })).json();
}
// List the models a provider exposes, via the backend (which proxies the provider's
// /v1/models — a direct browser call would be blocked by CORS and would leak the key).
export async function listModels(baseUrl: string, apiKey: string): Promise<string[]> {
  const r = await authed("/api/scaffold/models", {
    method: "POST", headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ baseUrl, apiKey }),
  });
  if (!r.ok) throw new Error(`couldn't list models (${r.status})`);
  return r.json();
}

export async function getMetrics(id: number): Promise<Sample[]> {
  return (await authed(`/api/jobs/${id}/metrics`)).json();
}
export async function getPhases(id: number): Promise<{ phase: string; ts_ms: number }[]> {
  return (await authed(`/api/jobs/${id}/phases`)).json();
}
export async function getPeaks(): Promise<Peak[]> {
  return (await authed("/api/metrics/peaks")).json();
}
export async function getSummarizer(): Promise<SummarizerInfo> {
  return (await authed("/api/summarizer")).json();
}
// `variant` ("baseline" | "patched") reads a compare job's per-variant log subdir.
export async function getLog(id: number, kind: string, variant?: string): Promise<string> {
  const q = variant ? `?variant=${encodeURIComponent(variant)}` : "";
  const r = await authed(`/api/jobs/${id}/logs/${kind}${q}`);
  return r.ok ? r.text() : `(no ${kind} log yet)`;
}
// Server-side syntax highlighting via arborium (tree-sitter, Rust-only).
// Returns highlighted HTML, or null for unsupported languages / parse errors.
export async function highlight(lang: string, code: string): Promise<string | null> {
  const r = await authed(`/api/highlight/${lang}`, { method: "POST", body: code });
  return r.ok ? r.text() : null;
}
export async function highlightCss(): Promise<string> {
  const r = await authed("/api/highlight.css");
  return r.ok ? r.text() : "";
}

// EventSource can't set headers; the token rides as a query param (Phase 5).
export function eventsUrl(id: number): string {
  const t = token();
  return `/api/jobs/${id}/events${t ? `?token=${encodeURIComponent(t)}` : ""}`;
}
// Process-wide stream that pings whenever the job list changes (push, not poll).
export function globalEventsUrl(): string {
  const t = token();
  return `/api/events${t ? `?token=${encodeURIComponent(t)}` : ""}`;
}

export const mib = (b: number) => (b / 1048576).toFixed(0);
export const gib = (b: number) => (b / 1073741824).toFixed(2);
