// Generated from https://lore.kernel.org/manifest.js.gz
export interface LkmlList { name: string; desc?: string; }

export const LKML_LISTS: LkmlList[] = [
  { name: "accel-config", desc: "Accel-Config development [epoch 0]" },
  { name: "acpica-devel", desc: "ACPICA development [epoch 0]" },
  { name: "alsa-devel", desc: "Alsa-Devel Archive on lore.kernel.org [epoch 0]" },
  { name: "amd-gfx", desc: "AMD-GFX Archive on lore.kernel.org [epoch 0]" },
  { name: "arm-scmi", desc: "Discuss SCMI firmware, SCMI drivers in Linux, U-boot, OP-TEE [epoch 0]" },
  { name: "asahi", desc: "Linux on Apple ARM platform development [epoch 0]" },
  { name: "ath10k", desc: "ATH10K Archive on lore.kernel.org [epoch 0]" },
  { name: "ath11k", desc: "ATH11K Archive on lore.kernel.org [epoch 0]" },
  { name: "ath12k", desc: "($INBOX_DIR/description missing) [epoch 0]" },
  { name: "ath9k-devel", desc: "Historical ath9k-devel archives [epoch 0]" },
  { name: "audit", desc: "Audit system development [epoch 0]" },
  { name: "autofs", desc: "AutoFS development [epoch 0]" },
  { name: "b4-sent", desc: "B4 Sent Patches" },
  { name: "b43-dev", desc: "b43-dev Archive on lore.kernel.org [epoch 0]" },
  { name: "backports", desc: "Linux backports project [epoch 0]" },
  { name: "barebox", desc: "mail archive of the barebox mailing list [epoch 0]" },
  { name: "batman", desc: "B.A.T.M.A.N Archive on lore.kernel.org [epoch 0]" },
  { name: "bitbake-devel", desc: "Openembedded Bitbake Development [epoch 0]" },
  { name: "bpf", desc: "BPF List [epoch 0]" },
  { name: "brcm80211", desc: "Linux brcm80211 wireless device drivers [epoch 0]" },
  { name: "bridge", desc: "Ethernet Bridge development [epoch 0]" },
  { name: "buildroot", desc: "Buildroot Archive on lore.kernel.org [epoch 0]" },
  { name: "c-std-porting", desc: "Porting Linux userspace to modern C [epoch 0]" },
  { name: "ccan", desc: "CCAN Archive on lore.kernel.org [epoch 0]" },
  { name: "ceph-devel", desc: "CEPH filesystem development [epoch 0]" },
  { name: "cgroups", desc: "Linux cgroups development [epoch 0]" },
  { name: "chrome-platform", desc: "Chrome platform driver development [epoch 0]" },
  { name: "cip-dev", desc: "CIP-dev Archive on lore.kernel.org [epoch 0]" },
  { name: "cluster-devel", desc: "Cluster-Devel Archive on lore.kernel.org [epoch 0]" },
  { name: "cocci", desc: "Coccinelle Archive on lore.kernel.org [epoch 0]" },
  { name: "coconut-svsm", desc: "Coconut-SVSM development mailing list [epoch 0]" },
  { name: "connman", desc: "ConnMan network manager [epoch 0]" },
  { name: "containers", desc: "Linux Container Development [epoch 0]" },
  { name: "cpufreq", desc: "cpufreq Archive on lore.kernel.org [epoch 0]" },
  { name: "criu", desc: "CRIU (Checkpoint/Restore in Userspace) mailing list [epoch 0]" },
  { name: "cryptsetup", desc: "Cryptsetup development [epoch 0]" },
  { name: "cti-tac", desc: "CTI Technical Advisory Committee [epoch 0]" },
  { name: "damon", desc: "DAMON development mailing list [epoch 0]" },
  { name: "dash", desc: "DASH Shell discussions [epoch 0]" },
  { name: "dccp", desc: "DCCP protocol discussions [epoch 0]" },
  { name: "ddprobe", desc: "List used for roundtrip monitoring [epoch 0]" },
  { name: "devicetree-compiler", desc: "Devicetree Compiler [epoch 0]" },
  { name: "devicetree-spec", desc: "Devicetree Spec [epoch 0]" },
  { name: "diamon-discuss", desc: "DiaMon (diagnostic and monitoring) [epoch 0]" },
  { name: "distributions", desc: "Forum for Linux distributions to discuss problems and share PSAs [epoch 0]" },
  { name: "dm-crypt", desc: "DM-Crypt Archive on lore.kernel.org [epoch 0]" },
  { name: "dm-devel", desc: "Linux Device Mapper development [epoch 0]" },
  { name: "dmaengine", desc: "DMA Engine development [epoch 0]" },
  { name: "dpdk-dev", desc: "DPDK-dev Archive on lore.kernel.org [epoch 1]" },
  { name: "drbd-announce", desc: "Distributed Replicated Block Device (DRBD) announcements [epoch 0]" },
  { name: "drbd-dev", desc: "Distributed Replicated Block Device (DRBD) development [epoch 0]" },
  { name: "dri-devel", desc: "dri-devel Archive on lore.kernel.org [epoch 2]" },
  { name: "driver-core", desc: "Linux driver-core infrastructure [epoch 0]" },
  { name: "dtrace", desc: "Linux DTrace development list [epoch 0]" },
  { name: "dwarves", desc: "Dwarves debugging tools [epoch 0]" },
  { name: "ecryptfs", desc: "EcryptFS development [epoch 0]" },
  { name: "ell", desc: "Embedded Linux Library [epoch 0]" },
  { name: "fio", desc: "Flexible I/O Tester development [epoch 0]" },
  { name: "fstests", desc: "FS/XFS testing framework [epoch 0]" },
  { name: "fsverity", desc: "Linux fsverity development list [epoch 0]" },
  { name: "fuego", desc: "Fuego test framework [epoch 0]" },
  { name: "fuse-devel", desc: "FILESYSTEM IN USERSPACE (FUSE) development [epoch 0]" },
  { name: "gfs2", desc: "gfs2 filesystem and dlm development [epoch 0]" },
  { name: "git", desc: "Git development [epoch 0]" },
  { name: "grub-devel", desc: "Grub Development Archive on lore.kernel.org [epoch 0]" },
  { name: "hail-devel", desc: "Hail cloud computing Development Archive on lore.kernel.org [epoch 0]" },
  { name: "historical-speck", desc: "Historical speck list archives [epoch 0]" },
  { name: "igt-dev", desc: "Igt-dev Archive on lore.kernel.org [epoch 0]" },
  { name: "imx", desc: "Linux kernel and device drivers for NXP i.MX platforms [epoch 0]" },
  { name: "initramfs", desc: "mkinitrd unification across distributions [epoch 0]" },
  { name: "intel-gfx", desc: "Intel-GFX Archive on lore.kernel.org [epoch 1]" },
  { name: "intel-wired-lan", desc: "Intel-Wired-Lan Archive on lore.kernel.org [epoch 0]" },
  { name: "intel-xe", desc: "Intel-XE Archive on lore.kernel.org [epoch 0]" },
  { name: "io-uring", desc: "Linux io-uring development [epoch 0]" },
  { name: "iwd", desc: "Wireless Daemon for Linux [epoch 0]" },
  { name: "kbd", desc: "Linux console tools development [epoch 0]" },
  { name: "kdevops", desc: "Linux kernel kdevops project [epoch 0]" },
  { name: "kernel-hardening", desc: "Kernel-hardening Archive on lore.kernel.org [epoch 0]" },
  { name: "kernel-janitors", desc: "Kernel development cleanups and similar janitorial tasks [epoch 0]" },
  { name: "kernel-testers", desc: "Kernel-testers Development Archive on lore.kernel.org [epoch 0]" },
  { name: "kernel-tls-handshake", desc: "Handshake for in-kernel TLS consumers [epoch 0]" },
  { name: "kernelci", desc: "KernelCI discussions [epoch 0]" },
  { name: "kernelnewbies", desc: "Kernel Newbies Archive on lore.kernel.org [epoch 0]" },
  { name: "kexec", desc: "Kexec Archive on lore.kernel.org [epoch 0]" },
  { name: "keyrings", desc: "Kernel keyring development [epoch 0]" },
  { name: "keys", desc: "Submissions of public keys to the kernel.org web of trust [epoch 0]" },
  { name: "ksummit", desc: "Linux Kernel Summit discussions [epoch 0]" },
  { name: "kvm", desc: "Kernel KVM virtualization development [epoch 1]" },
  { name: "kvm-ia64", desc: "Kvm-ia64 Development Archive on lore.kernel.org [epoch 0]" },
  { name: "kvm-ppc", desc: "Kernel KVM-PPC virtualization development [epoch 0]" },
  { name: "kvm-riscv", desc: "KVM-RISCV Archive on lore.kernel.org [epoch 0]" },
  { name: "kvmarm", desc: "Linux KVM/arm64 development list [epoch 0]" },
  { name: "landlock", desc: "Landlock LSM user space discussions [epoch 0]" },
  { name: "lartc", desc: "Linux Advanced Routing and Traffic Control list [epoch 0]" },
  { name: "lch", desc: "Linux CH - Switzerland [epoch 0]" },
  { name: "liba2i", desc: "String-to-numeric library [epoch 0]" },
  { name: "linux-8086", desc: "Linux-8086 Development Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-acpi", desc: "Linux ACPI [epoch 0]" },
  { name: "linux-admin", desc: "Linux-admin Development Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-alpha", desc: "Alpha arch development list [epoch 0]" },
  { name: "linux-amlogic", desc: "Linux-Amlogic Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-api", desc: "Linux userland API discussions [epoch 0]" },
  { name: "linux-arch", desc: "Generic Linux architectural discussions [epoch 0]" },
  { name: "linux-arm-kernel", desc: "Linux-ARM-Kernel Archive on lore.kernel.org [epoch 3]" },
  { name: "linux-arm-msm", desc: "Linux ARM-MSM sub-architecture [epoch 0]" },
  { name: "linux-aspeed", desc: "Linux-Aspeed Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-assembly", desc: "Linux assembly list [epoch 0]" },
  { name: "linux-audit", desc: "Linux-audit Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-bcache", desc: "Linux bcache driver list [epoch 0]" },
  { name: "linux-bcachefs", desc: "Linux bcachefs list [epoch 0]" },
  { name: "linux-block", desc: "Linux block layer [epoch 0]" },
  { name: "linux-bluetooth", desc: "Linux bluetooth development [epoch 0]" },
  { name: "linux-btrace", desc: "Linux btrace development [epoch 0]" },
  { name: "linux-btrfs", desc: "Linux Btrfs filesystem development [epoch 0]" },
  { name: "linux-bugs", desc: "Generic list for bug discussions [epoch 0]" },
  { name: "linux-c-programming", desc: "Linux-c-programming Development Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-can", desc: "Linux CAN drivers development [epoch 0]" },
  { name: "linux-cifs", desc: "Linux CIFS filesystem development [epoch 0]" },
  { name: "linux-clk", desc: "Linux clock framework development [epoch 0]" },
  { name: "linux-coco", desc: "Linux Confidential Computing Development [epoch 0]" },
  { name: "linux-config", desc: "Linux-config Development Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-console", desc: "Linux-console Development Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-crypto", desc: "Linux cryptographic layer development [epoch 0]" },
  { name: "linux-csky", desc: "Linux C-SKY architecture development [epoch 0]" },
  { name: "linux-cve-announce", desc: "Linux kernel CVE announcements [epoch 0]" },
  { name: "linux-cxl", desc: "Linux CXL [epoch 0]" },
  { name: "linux-debuggers", desc: "Linux debuggers [epoch 0]" },
  { name: "linux-devicetree", desc: "Devicetree [epoch 3]" },
  { name: "linux-diald", desc: "Linux-diald Development Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-doc", desc: "Linux Documentation [epoch 0]" },
  { name: "linux-edac", desc: "Linux EDAC development [epoch 0]" },
  { name: "linux-efi", desc: "Linux EFI development [epoch 0]" },
  { name: "linux-embedded", desc: "Embedded Linux development [epoch 0]" },
  { name: "linux-erofs", desc: "Linux-EROFS Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-ext4", desc: "Linux EXT4 FS development [epoch 0]" },
  { name: "linux-f2fs-devel", desc: "Linux-f2fs-devel Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-fbdev", desc: "Linux Framebuffer Layer development [epoch 0]" },
  { name: "linux-firmware", desc: "Linux-Firmware Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-fpga", desc: "Linux FPGA development [epoch 0]" },
  { name: "linux-fscrypt", desc: "Linux FSCRYPT development [epoch 0]" },
  { name: "linux-fsdevel", desc: "Linux filesystem development [epoch 1]" },
  { name: "linux-gcc", desc: "Linux GCC discussions [epoch 0]" },
  { name: "linux-gpio", desc: "Linux GPIO subsystem development [epoch 0]" },
  { name: "linux-hams", desc: "Linux HAM/Amateur Radio development [epoch 0]" },
  { name: "linux-hardening", desc: "Linux Hardening [epoch 0]" },
  { name: "linux-hexagon", desc: "Linux Hexagon architecture development [epoch 0]" },
  { name: "linux-hotplug", desc: "Linux Hotplug development [epoch 0]" },
  { name: "linux-hwmon", desc: "Linux Hardware Monitor development [epoch 0]" },
  { name: "linux-hyperv", desc: "Linux-HyperV List [epoch 0]" },
  { name: "linux-i2c", desc: "Linux I2C development [epoch 0]" },
  { name: "linux-i3c", desc: "Linux-i3c Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-ia64", desc: "Linux IA64 platform development [epoch 0]" },
  { name: "linux-ide", desc: "Linux ATA/IDE development [epoch 0]" },
  { name: "linux-iio", desc: "Linux IIO development [epoch 0]" },
  { name: "linux-input", desc: "Linux Input/HID development [epoch 0]" },
  { name: "linux-integrity", desc: "Linux Integrity Measurement development [epoch 0]" },
  { name: "linux-iommu", desc: "Linux IOMMU Development [epoch 0]" },
  { name: "linux-kbuild", desc: "Linux kbuild/kconfig development [epoch 0]" },
  { name: "linux-kernel-announce", desc: "Linux kernel announcements [epoch 0]" },
  { name: "linux-kernel-mentees", desc: "Linux Kernel Mentees list [epoch 0]" },
  { name: "linux-kselftest", desc: "Linux Kernel Selftest development [epoch 0]" },
  { name: "linux-laptop", desc: "Linux laptop Discussion Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-leds", desc: "Linux LED subsystem development [epoch 0]" },
  { name: "linux-lvm", desc: "Linux LVM users [epoch 0]" },
  { name: "linux-m68k", desc: "Linux M68K Architecture development [epoch 0]" },
  { name: "linux-man", desc: "Linux Manual Pages development [epoch 0]" },
  { name: "linux-media", desc: "Linux Media Controller development [epoch 1]" },
  { name: "linux-mediatek", desc: "Linux-mediatek Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-metag", desc: "Linux Metag architecture Discussion Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-mips", desc: "Linux MIPS Architecture development [epoch 0]" },
  { name: "linux-mm", desc: "Linux-mm Archive on lore.kernel.org [epoch 1]" },
  { name: "linux-mmc", desc: "Linux MultiMedia Card development [epoch 0]" },
  { name: "linux-modules", desc: "Linux Modules [epoch 0]" },
  { name: "linux-msdos", desc: "Linux MS DOS discussions [epoch 0]" },
  { name: "linux-mtd", desc: "Linux-mtd Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-newbie", desc: "Linux Newbie help [epoch 0]" },
  { name: "linux-next", desc: "Linux-Next discussions [epoch 0]" },
  { name: "linux-nfc", desc: "Linux-NFC Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-nfs", desc: "Linux NFS development [epoch 0]" },
  { name: "linux-nilfs", desc: "Linux NILFS development [epoch 0]" },
  { name: "linux-numa", desc: "Linux NUMA userland tools development [epoch 0]" },
  { name: "linux-nvdimm", desc: "Linux-NVDIMM Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-nvme", desc: "Linux-NVME Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-omap", desc: "Linux on ARM based TI OMAP SoCs [epoch 0]" },
  { name: "linux-oxnas", desc: "linux-oxnas archives [epoch 0]" },
  { name: "linux-parisc", desc: "Linux PARISC architecture development [epoch 0]" },
  { name: "linux-patches", desc: "Archive-only list for patches [epoch 0]" },
  { name: "linux-pci", desc: "Linux PCI subsystem development [epoch 0]" },
  { name: "linux-perf-users", desc: "Linux Perf Users [epoch 0]" },
  { name: "linux-phy", desc: "Linux-PHY Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-pm", desc: "Linux Power Management development [epoch 0]" },
  { name: "linux-ppp", desc: "Linux PPP protocol development [epoch 0]" },
  { name: "linux-pwm", desc: "Linux PWM subsystem development [epoch 0]" },
  { name: "linux-raid", desc: "Linux RAID subsystem development [epoch 0]" },
  { name: "linux-rdma", desc: "Linux RDMA and InfiniBand development [epoch 0]" },
  { name: "linux-remoteproc", desc: "Linux Remote Processor Subsystem development [epoch 0]" },
  { name: "linux-renesas-soc", desc: "Linux Renesas SOC kernel development [epoch 0]" },
  { name: "linux-riscv", desc: "Linux-RISC-V Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-rockchip", desc: "Linux-Rockchip Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-rt-devel", desc: "Linux real-time development [epoch 0]" },
  { name: "linux-rt-users", desc: "Linux RT Users [epoch 0]" },
  { name: "linux-rtc", desc: "Linux RTC [epoch 0]" },
  { name: "linux-s390", desc: "Linux s390 Architecture development [epoch 0]" },
  { name: "linux-safety", desc: "Linux-Safety Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-samsung-soc", desc: "Linux Samsung SOC development [epoch 0]" },
  { name: "linux-scsi", desc: "Linux SCSI subsystem development [epoch 0]" },
  { name: "linux-sctp", desc: "Linux SCTP protocol development [epoch 0]" },
  { name: "linux-security-module", desc: "Linux Security Modules development [epoch 0]" },
  { name: "linux-serial", desc: "Linux Serial subsystem development [epoch 0]" },
  { name: "linux-sgx", desc: "Intel SGX development [epoch 0]" },
  { name: "linux-sh", desc: "SUPERH platform development [epoch 0]" },
  { name: "linux-smp", desc: "Symmetric Multiprocessing (SMP) development [epoch 0]" },
  { name: "linux-snps-arc", desc: "Linux SNPS ARC Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-sound", desc: "Linux Sound subsystem development [epoch 0]" },
  { name: "linux-sparse", desc: "Linux SPARSE checker discussions [epoch 0]" },
  { name: "linux-spdx", desc: "Linux Licenses and SPDX discussions [epoch 0]" },
  { name: "linux-spi", desc: "Linux SPI subsystem development [epoch 0]" },
  { name: "linux-staging", desc: "Linux kernel staging patches [epoch 0]" },
  { name: "linux-sunxi", desc: "ARM Sunxi Platform Development [epoch 0]" },
  { name: "linux-tegra", desc: "Linux Tegra architecture development [epoch 0]" },
  { name: "linux-toolchains", desc: "Linux toolchain discussions [epoch 0]" },
  { name: "linux-trace-devel", desc: "Linux Trace Development [epoch 0]" },
  { name: "linux-trace-kernel", desc: "Linux Trace Kernel [epoch 0]" },
  { name: "linux-trace-users", desc: "Linux Trace Users [epoch 0]" },
  { name: "linux-um", desc: "linux-um archives [epoch 0]" },
  { name: "linux-unionfs", desc: "Linux Overlay Filesystem development [epoch 0]" },
  { name: "linux-usb", desc: "Linux USB [epoch 0]" },
  { name: "linux-watchdog", desc: "Linux Watchdog driver development [epoch 0]" },
  { name: "linux-wireless", desc: "Linux wireless drivers development [epoch 0]" },
  { name: "linux-wpan", desc: "Linux IEEE 802.15.4 and 6LoWPAN development [epoch 0]" },
  { name: "linux-x11", desc: "Linux X11 Discussion Archive on lore.kernel.org [epoch 0]" },
  { name: "linux-x25", desc: "Linux X.25 subsystem development [epoch 0]" },
  { name: "linux-xfs", desc: "Linux XFS filesystem development [epoch 0]" },
  { name: "linuxppc-dev", desc: "LinuxPPC-Dev Archive on lore.kernel.org [epoch 0]" },
  { name: "live-patching", desc: "Live Patching [epoch 0]" },
  { name: "lkml", desc: "The Linux Kernel Mailing List [epoch 7]" },
  { name: "lkmm", desc: "Linux Kernel Memory Consistency Model [epoch 0]" },
  { name: "llvm", desc: "Building the Linux kernel with Clang and LLVM [epoch 0]" },
  { name: "lm-sensors", desc: "LM Sensors development [epoch 0]" },
  { name: "loongarch", desc: "LoongArch architecture development [epoch 0]" },
  { name: "ltp", desc: "Linux Test Project [epoch 0]" },
  { name: "lttng-dev", desc: "lttng-dev Archive on lore.kernel.org [epoch 0]" },
  { name: "lustre-devel", desc: "Lustre-devel archive on lore.kernel.org [epoch 0]" },
  { name: "lvfs-announce", desc: "Linux Vendor Firmware Service (LVFS) announcements [epoch 0]" },
  { name: "lvfs-general", desc: "Linux Vendor Firmware Service (LVFS) development [epoch 0]" },
  { name: "lvm-devel", desc: "Linux LVM developers [epoch 0]" },
  { name: "lvs-devel", desc: "LVS and IPVS development [epoch 0]" },
  { name: "mailbox", desc: "Linux mailbox device drivers [epoch 0]" },
  { name: "mfd", desc: "Linux Multi-Functional Device Drivers (MFD) [epoch 0]" },
  { name: "mhi", desc: "Linux MHI Development [epoch 0]" },
  { name: "mlmmj", desc: "MLMMJ Mailing List Manager [epoch 0]" },
  { name: "mm-commits", desc: "Linux MM tree latest commits [epoch 0]" },
  { name: "mptcp", desc: "MPTCP Linux Development [epoch 0]" },
  { name: "multikernel", desc: "Multikernel Architecture for Linux Kernel [epoch 0]" },
  { name: "netdev", desc: "Netdev List [epoch 3]" },
  { name: "netfilter", desc: "Linux Netfilter discussions [epoch 0]" },
  { name: "netfilter-devel", desc: "Linux Netfilter development [epoch 0]" },
  { name: "netfs", desc: "Linux network filesystem support library [epoch 0]" },
  { name: "nil-migration", desc: "nil-migration development mailing list [epoch 0]" },
  { name: "nouveau", desc: "Nouveau Archive on lore.kernel.org [epoch 0]" },
  { name: "nova-gpu", desc: "NVIDIA GPU driver infrastructure [epoch 0]" },
  { name: "ntb", desc: "Linux PCI Non-Transparent Bridge framework and drivers [epoch 0]" },
  { name: "ntfs3", desc: "NTFS3 file system kernel mode driver [epoch 0]" },
  { name: "nvdimm", desc: "NVDIMM Device and Persistent Memory development [epoch 0]" },
  { name: "ocfs2-devel", desc: "Linux ocfs2 filesystem development [epoch 0]" },
  { name: "oe-chipsec", desc: "CHIPSEC Discussion List [epoch 0]" },
  { name: "oe-kbuild", desc: "0 day kernel build service [epoch 0]" },
  { name: "oe-kbuild-all", desc: "kbuild Development List [epoch 0]" },
  { name: "oe-linux-nfc", desc: "NFC on Linux [epoch 0]" },
  { name: "oe-lkp", desc: "Linux Kernel Performance [epoch 0]" },
  { name: "ofono", desc: "Open Source Telephony [epoch 0]" },
  { name: "op-tee", desc: "OP-TEE Archive on lore.kernel.org [epoch 0]" },
  { name: "opae", desc: "Open Programmable Acceleration Engine [epoch 0]" },
  { name: "openbmc", desc: "Openbmc Archive on lore.kernel.org [epoch 0]" },
  { name: "openembedded-core", desc: "Openembedded Core Discussions [epoch 0]" },
  { name: "openembedded-devel", desc: "Openembedded Devel Discussions [epoch 0]" },
  { name: "openrisc", desc: "Linux OpenRISC platform development [epoch 0]" },
  { name: "opensbi", desc: "OpenSBI Archive on lore.kernel.org [epoch 0]" },
  { name: "openvpn-devel", desc: "OpenVPN devel archives [epoch 0]" },
  { name: "outreachy", desc: "Outreachy Linux Kernel Community [epoch 0]" },
  { name: "perfbook", desc: "Discussions of the Parallel Programming book [epoch 0]" },
  { name: "phone-devel", desc: "Linux smartphone development [epoch 0]" },
  { name: "platform-driver-x86", desc: "X86 platform drivers [epoch 0]" },
  { name: "poky", desc: "Poky Project Discussions [epoch 0]" },
  { name: "powertop", desc: "powertop - power analysis tool [epoch 0]" },
  { name: "printing-architecture", desc: "Printing architecture under Linux [epoch 0]" },
  { name: "printing-users", desc: "Linux printing list for end users to discuss printing issues and potential feature requests [epoch 0]" },
  { name: "qemu-arm", desc: "QEMU-Arm Archive on lore.kernel.org [epoch 0]" },
  { name: "qemu-devel", desc: "QEMU-Devel Archive on lore.kernel.org [epoch 0]" },
  { name: "qemu-riscv", desc: "QEMU-Riscv Archive on lore.kernel.org [epoch 0]" },
  { name: "qemu-rust", desc: "QEMU-Rust Archive on lore.kernel.org [epoch 0]" },
  { name: "qemu-trivial", desc: "QEMU-Trivial Archive on lore.kernel.org [epoch 0]" },
  { name: "quic", desc: "Linux QUIC protocol development [epoch 0]" },
  { name: "radiotap", desc: "RadioTap Archive on lore.kernel.org [epoch 0]" },
  { name: "rcu", desc: "Linux RCU subsystem development [epoch 0]" },
  { name: "regressions", desc: "Linux kernel regressions [epoch 0]" },
  { name: "reiserfs-devel", desc: "Linux ReiserFS filesystem (obsolete) [epoch 0]" },
  { name: "rpdfs-devel", desc: "RapidFS Filesystem Development [epoch 0]" },
  { name: "rust-for-linux", desc: "Rust for Linux List [epoch 0]" },
  { name: "sashiko", desc: "Sashiko discussions [epoch 0]" },
  { name: "sashiko-reviews", desc: "Sashiko Reviews [epoch 0]" },
  { name: "sched-ext", desc: "Sched_ext development [epoch 0]" },
  { name: "selinux", desc: "SELinux Security Module development [epoch 0]" },
  { name: "selinux-refpolicy", desc: "SELinux Reference Policy development [epoch 0]" },
  { name: "signatures", desc: "Signatures Archive on lore.kernel.org [epoch 0]" },
  { name: "smatch", desc: "Smatch (Semantic Matching Tool) development [epoch 0]" },
  { name: "soc", desc: "Linux SOC development [epoch 0]" },
  { name: "sophgo", desc: "Linux Sophgo SoC development [epoch 0]" },
  { name: "spacemit", desc: "Linux SpacemiT device drivers [epoch 0]" },
  { name: "sparclinux", desc: "SPARC and UltraSPARC platform development [epoch 0]" },
  { name: "spdk", desc: "Storage Performance Development Kit (SPDK) [epoch 0]" },
  { name: "stable", desc: "Linux kernel -stable discussions [epoch 2]" },
  { name: "stable-rt", desc: "RealTime Linux kernel -stable discussions [epoch 0]" },
  { name: "stgt", desc: "SCSI target infrastructure discussions [epoch 0]" },
  { name: "syzbot", desc: "Archive-only list for syzbot [epoch 0]" },
  { name: "target-devel", desc: "SCSI target development [epoch 0]" },
  { name: "tech-board-discuss", desc: "Technical Advisory Board (TAB) public discussions [epoch 0]" },
  { name: "timestamp", desc: "Linux HTE (hardware timestamp engine) subsytem [epoch 0]" },
  { name: "tools", desc: "Linux maintainer tooling and workflows [epoch 0]" },
  { name: "tpm-protocol", desc: "TPM protocol marshaller and unmarshaller [epoch 0]" },
  { name: "tpm2", desc: "TPM2 (Trusted Platform Module) userspace development [epoch 0]" },
  { name: "tpmdd-devel", desc: "tpmdd-devel Archive on lore.kernel.org [epoch 0]" },
  { name: "trinity", desc: "Trinity fuzzer tool discussions [epoch 0]" },
  { name: "u-boot", desc: "U-Boot Archive on lore.kernel.org [epoch 1]" },
  { name: "u-boot-amlogic", desc: "u-boot-amlogic archives [epoch 0]" },
  { name: "ultralinux", desc: "Ultralinux archive on lore.kernel.org [epoch 0]" },
  { name: "util-linux", desc: "Util-Linux package development [epoch 0]" },
  { name: "v9fs", desc: "Linux 9p file system development [epoch 0]" },
  { name: "virtio-comment", desc: "Discussion of the VIRTIO specification [epoch 0]" },
  { name: "virtio-dev", desc: "Discussion of the implementations of VIRTIO specification [epoch 0]" },
  { name: "virtio-fs", desc: "Development discussions about virtio-fs [epoch 0]" },
  { name: "virtualization", desc: "Linux virtualization list [epoch 0]" },
  { name: "wireguard", desc: "WireGuard Archive on lore.kernel.org [epoch 0]" },
  { name: "wireless-regdb", desc: "Wireless-regdb Archive on lore.kernel.org [epoch 0]" },
  { name: "workflows", desc: "Maintainer workflows discussions [epoch 0]" },
  { name: "x86-cpuid", desc: "x86-cpuid.org development mailing list [epoch 0]" },
  { name: "xdp-newbies", desc: "XDP Newbie developer discussions [epoch 0]" },
  { name: "xdp2", desc: "XDP2 discussion & development [epoch 0]" },
  { name: "xen-devel", desc: "Xen-Devel Archive on lore.kernel.org [epoch 0]" },
  { name: "xenomai", desc: "Xenomai real-time core development [epoch 0]" },
  { name: "xfs-stable", desc: "XFS stable LTS mailing list [epoch 0]" },
  { name: "yocto", desc: "Yocto Project Discussions [epoch 0]" },
  { name: "yocto-docs", desc: "Yocto Project Documentation [epoch 0]" },
  { name: "yocto-meta-arago", desc: "Yocto Meta Arago [epoch 0]" },
  { name: "yocto-meta-arm", desc: "Yocto Meta Arm [epoch 0]" },
  { name: "yocto-meta-freescale", desc: "Yocto Meta Freescale [epoch 0]" },
  { name: "yocto-meta-ti", desc: "Yocto Meta TI [epoch 0]" },
  { name: "yocto-meta-virtualization", desc: "Yocto Meta Virtualization [epoch 0]" },
  { name: "yocto-patches", desc: "Patches for Yocto layers and components that do not have their own list [epoch 0]" },
  { name: "yocto-status", desc: "Yocto Project weekly status reports [epoch 0]" },
  { name: "yocto-toaster", desc: "Yocto Toaster [epoch 0]" },
];
