//! DuckDB-backed job index, event log, and metrics time-series.
use std::sync::{Arc, Mutex};

use anyhow::Result;
use duckdb::Connection;
use serde::Serialize;

#[derive(Clone)]
pub struct Db {
    conn: Arc<Mutex<Connection>>,
}

#[derive(Serialize, Clone)]
pub struct Job {
    pub id: i64,
    pub created_ms: i64,
    pub started_ms: Option<i64>,
    pub finished_ms: Option<i64>,
    pub status: String,
    pub phase: Option<String>,
    pub exit_code: Option<i64>,
    pub ram_peak: i64,
    pub disk_peak: i64,
    pub reaped_ms: Option<i64>,
    /// Legacy single summary column, no longer written (kept for old rows).
    pub summary: Option<String>,
    /// Natural-language summaries (see src/summarize.rs), each from its own model:
    /// one sentence on what the reproducer tests (set at job start), one sentence on
    /// what happened (set at job end), and a two-paragraph "why it failed" detail.
    pub repro_summary: Option<String>,
    pub result_summary: Option<String>,
    pub detail: Option<String>,
    /// Provenance, set for jobs created from an external source (LKML candidate): the
    /// thread/permalink to link to, and the mail subject to label the row. NULL otherwise.
    pub source_url: Option<String>,
    /// Provenance title: the LKML mail subject for LKML jobs, else NULL.
    pub title: Option<String>,
    /// Terse two-word title generated by the summarizer at job start; shown inline after #id.
    pub short_title: Option<String>,
    /// Per-summary generation metadata as raw JSON ({"title":{"ms","tokens","model"},...}),
    /// merged field-by-field as summaries complete. NULL until the first summary lands.
    pub summary_meta: Option<String>,
}

/// A cover letter found on LKML whose frontmatter matches the reproducer spec, shown
/// on the site as a runnable candidate. `bundle` is omitted from the API list (it can
/// be large); the UI only needs the metadata + link.
#[derive(Serialize, Clone)]
pub struct Candidate {
    pub msgid: String,
    pub list: Option<String>,
    pub title: Option<String>,
    pub source_url: String,
    pub detected_ms: i64,
    pub job_id: Option<i64>,
}

/// One per-server summary for a job (every backend's output for a field). The legacy
/// per-field columns on `jobs` carry the primary backend's copy; this table carries
/// all of them, surfaced by the UI's "see all models" expander.
#[derive(Serialize, Clone)]
pub struct JobSummary {
    pub field: String,
    pub server: String,
    pub text: String,
    pub ms: Option<i64>,
    pub tokens: Option<i64>,
    pub model: Option<String>,
}

#[derive(Serialize, Clone)]
pub struct Sample {
    pub ts_ms: i64,
    pub rss_bytes: i64,
    pub disk_bytes: i64,
}

#[derive(Serialize, Clone)]
pub struct Peak {
    pub id: i64,
    pub ram_peak: i64,
    pub disk_peak: i64,
    pub status: String,
}

impl Db {
    pub fn open(path: &std::path::Path) -> Result<Self> {
        let conn = Connection::open(path)?;
        conn.execute_batch(
            r#"
            CREATE SEQUENCE IF NOT EXISTS job_seq START 1;
            CREATE TABLE IF NOT EXISTS jobs (
                id BIGINT PRIMARY KEY,
                created_ms BIGINT NOT NULL,
                started_ms BIGINT,
                finished_ms BIGINT,
                status VARCHAR NOT NULL,
                phase VARCHAR,
                exit_code BIGINT,
                ram_peak BIGINT NOT NULL DEFAULT 0,
                disk_peak BIGINT NOT NULL DEFAULT 0,
                submitter VARCHAR
            );
            ALTER TABLE jobs ADD COLUMN IF NOT EXISTS reaped_ms BIGINT;
            ALTER TABLE jobs ADD COLUMN IF NOT EXISTS summary VARCHAR;
            -- Provenance for jobs created from an external source (e.g. an LKML
            -- candidate): the thread/permalink and the mail subject, surfaced as a
            -- link + label in the UI. NULL for plain paste-box submissions.
            ALTER TABLE jobs ADD COLUMN IF NOT EXISTS source_url VARCHAR;
            ALTER TABLE jobs ADD COLUMN IF NOT EXISTS title VARCHAR;
            -- Per-model summaries: reproducer one-liner (start), result one-liner
            -- (end), and a two-paragraph "why it failed" detail (end), replacing the
            -- single overwritten `summary` column above.
            ALTER TABLE jobs ADD COLUMN IF NOT EXISTS repro_summary VARCHAR;
            ALTER TABLE jobs ADD COLUMN IF NOT EXISTS result_summary VARCHAR;
            ALTER TABLE jobs ADD COLUMN IF NOT EXISTS detail VARCHAR;
            -- Terse two-word title generated by the summarizer, shown inline after #id.
            ALTER TABLE jobs ADD COLUMN IF NOT EXISTS short_title VARCHAR;
            -- Per-summary generation metadata as a JSON object keyed by field
            -- ({"title":{"ms","tokens","model"},...}); drives the UI hover tooltip.
            ALTER TABLE jobs ADD COLUMN IF NOT EXISTS summary_meta VARCHAR;
            -- One row per (job, summary field, backend server): every backend's
            -- output. The legacy per-field columns above hold the primary backend's
            -- copy; this holds all of them for the UI's "see all models" view.
            CREATE TABLE IF NOT EXISTS job_summaries (
                job_id BIGINT NOT NULL, field VARCHAR NOT NULL, server VARCHAR NOT NULL,
                text VARCHAR NOT NULL, ms BIGINT, tokens BIGINT, model VARCHAR,
                created_ms BIGINT NOT NULL,
                PRIMARY KEY (job_id, field, server)
            );
            CREATE TABLE IF NOT EXISTS events (
                job_id BIGINT NOT NULL, ts_ms BIGINT NOT NULL,
                phase VARCHAR NOT NULL, message VARCHAR
            );
            CREATE TABLE IF NOT EXISTS metrics (
                job_id BIGINT NOT NULL, ts_ms BIGINT NOT NULL,
                rss_bytes BIGINT NOT NULL, disk_bytes BIGINT NOT NULL
            );
            -- Every LKML message id the monitor has already evaluated, so it never
            -- re-fetches/re-parses one across polls (qualifying or not).
            CREATE TABLE IF NOT EXISTS lkml_seen (
                msgid VARCHAR PRIMARY KEY, list VARCHAR, seen_ms BIGINT NOT NULL
            );
            -- Cover letters whose frontmatter matched the reproducer spec: shown on
            -- the site as runnable candidates. `bundle` is the cover-letter text with
            -- `thread:` already injected, so Run is a pass-through to create_job.
            CREATE TABLE IF NOT EXISTS candidates (
                msgid VARCHAR PRIMARY KEY, list VARCHAR, title VARCHAR,
                source_url VARCHAR NOT NULL, bundle VARCHAR NOT NULL,
                detected_ms BIGINT NOT NULL, job_id BIGINT
            );
            "#,
        )?;
        Ok(Self { conn: Arc::new(Mutex::new(conn)) })
    }

    fn lock(&self) -> std::sync::MutexGuard<'_, Connection> {
        self.conn.lock().expect("db mutex poisoned")
    }

    pub fn create_job(&self, now_ms: i64, submitter: Option<&str>) -> Result<i64> {
        self.create_job_full(now_ms, submitter, None, None)
    }

    /// Like `create_job`, but also records provenance (source link + title) for jobs
    /// created from an external source such as an LKML candidate.
    pub fn create_job_full(&self, now_ms: i64, submitter: Option<&str>,
                           source_url: Option<&str>, title: Option<&str>) -> Result<i64> {
        let c = self.lock();
        let id: i64 = c.query_row("SELECT nextval('job_seq')", [], |r| r.get(0))?;
        c.execute(
            "INSERT INTO jobs (id, created_ms, status, submitter, source_url, title)
             VALUES (?, ?, 'queued', ?, ?, ?)",
            duckdb::params![id, now_ms, submitter, source_url, title],
        )?;
        Ok(id)
    }

    pub fn set_running(&self, id: i64, now_ms: i64) -> Result<()> {
        self.lock().execute(
            "UPDATE jobs SET status='running', started_ms=? WHERE id=?",
            duckdb::params![now_ms, id],
        )?;
        Ok(())
    }

    pub fn set_phase(&self, id: i64, phase: &str) -> Result<()> {
        self.lock()
            .execute("UPDATE jobs SET phase=? WHERE id=?", duckdb::params![phase, id])?;
        Ok(())
    }

    pub fn finish(&self, id: i64, now_ms: i64, status: &str, exit: Option<i64>,
                  ram_peak: i64, disk_peak: i64) -> Result<()> {
        self.lock().execute(
            "UPDATE jobs SET status=?, finished_ms=?, exit_code=?, ram_peak=?, disk_peak=? WHERE id=?",
            duckdb::params![status, now_ms, exit, ram_peak, disk_peak, id],
        )?;
        Ok(())
    }

    /// Set a single summary column. Column name is a fixed literal (never user input).
    fn set_summary_col(&self, id: i64, col: &str, text: &str) -> Result<()> {
        self.lock()
            .execute(&format!("UPDATE jobs SET {col}=? WHERE id=?"), duckdb::params![text, id])?;
        Ok(())
    }

    /// Set a summary column only if it's still NULL (a non-primary backend's
    /// best-effort fallback so the default view is never blank when the primary fails).
    /// Column name is a fixed literal (never user input).
    fn set_summary_col_if_null(&self, id: i64, col: &str, text: &str) -> Result<()> {
        self.lock().execute(
            &format!("UPDATE jobs SET {col}=? WHERE id=? AND {col} IS NULL"),
            duckdb::params![text, id],
        )?;
        Ok(())
    }

    /// Fill a legacy per-field column from a non-primary backend only if empty.
    /// `field` is the summary field ("title"|"repro"|"result"|"detail").
    pub fn set_summary_fallback(&self, id: i64, field: &str, text: &str) -> Result<()> {
        let col = match field {
            "title" => "short_title",
            "repro" => "repro_summary",
            "result" => "result_summary",
            "detail" => "detail",
            _ => return Ok(()),
        };
        self.set_summary_col_if_null(id, col, text)
    }

    /// Upsert one backend's summary for a (job, field, server) into `job_summaries`.
    pub fn set_job_summary(&self, id: i64, field: &str, server: &str, text: &str,
                           ms: u64, tokens: u32, model: &str, now_ms: i64) -> Result<()> {
        self.lock().execute(
            "INSERT INTO job_summaries (job_id, field, server, text, ms, tokens, model, created_ms)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?)
             ON CONFLICT (job_id, field, server)
             DO UPDATE SET text=excluded.text, ms=excluded.ms, tokens=excluded.tokens,
                           model=excluded.model, created_ms=excluded.created_ms",
            duckdb::params![id, field, server, text, ms as i64, tokens as i64, model, now_ms],
        )?;
        Ok(())
    }

    /// All per-server summaries for a job (every backend, every field), newest first.
    pub fn get_job_summaries(&self, id: i64) -> Result<Vec<JobSummary>> {
        let c = self.lock();
        let mut stmt = c.prepare(
            "SELECT field, server, text, ms, tokens, model FROM job_summaries
             WHERE job_id=? ORDER BY field, server",
        )?;
        let mut rows = stmt.query(duckdb::params![id])?;
        let mut out = Vec::new();
        while let Some(r) = rows.next()? {
            out.push(JobSummary {
                field: r.get(0)?, server: r.get(1)?, text: r.get(2)?,
                ms: r.get(3)?, tokens: r.get(4)?, model: r.get(5)?,
            });
        }
        Ok(out)
    }

    pub fn set_short_title(&self, id: i64, text: &str) -> Result<()> {
        self.set_summary_col(id, "short_title", text)
    }
    pub fn set_repro(&self, id: i64, text: &str) -> Result<()> {
        self.set_summary_col(id, "repro_summary", text)
    }
    pub fn set_result(&self, id: i64, text: &str) -> Result<()> {
        self.set_summary_col(id, "result_summary", text)
    }
    pub fn set_detail(&self, id: i64, text: &str) -> Result<()> {
        self.set_summary_col(id, "detail", text)
    }

    /// Merge one field's generation metadata into the `summary_meta` JSON object.
    /// Read-modify-write under a single held lock so the concurrent start (title+repro)
    /// and end (result+detail) pairs don't clobber each other's entries.
    pub fn set_summary_meta(&self, id: i64, field: &str, ms: u64, tokens: u32, model: &str) -> Result<()> {
        let c = self.lock();
        let cur: Option<String> = c
            .query_row("SELECT summary_meta FROM jobs WHERE id=?", duckdb::params![id],
                       |r| r.get::<_, Option<String>>(0))
            .unwrap_or(None);
        let mut obj = cur
            .and_then(|s| serde_json::from_str::<serde_json::Value>(&s).ok())
            .unwrap_or_else(|| serde_json::json!({}));
        // Human-readable duration in a convenient unit (e.g. "17s", "2m 3s"); rounded
        // to whole seconds once past a second so the tooltip isn't noisy with millis.
        let dur = if ms >= 1000 {
            std::time::Duration::from_secs((ms + 500) / 1000)
        } else {
            std::time::Duration::from_millis(ms)
        };
        let took = humantime::format_duration(dur).to_string();
        obj[field] = serde_json::json!({"ms": ms, "took": took, "tokens": tokens, "model": model});
        c.execute("UPDATE jobs SET summary_meta=? WHERE id=?",
                  duckdb::params![obj.to_string(), id])?;
        Ok(())
    }

    pub fn add_event(&self, id: i64, ts_ms: i64, phase: &str, message: &str) -> Result<()> {
        self.lock().execute(
            "INSERT INTO events (job_id, ts_ms, phase, message) VALUES (?, ?, ?, ?)",
            duckdb::params![id, ts_ms, phase, message],
        )?;
        Ok(())
    }

    pub fn get_events(&self, id: i64) -> Result<Vec<(i64, String)>> {
        let c = self.lock();
        let mut stmt = c.prepare(
            "SELECT ts_ms, phase FROM events WHERE job_id=? ORDER BY ts_ms",
        )?;
        let mut rows = stmt.query(duckdb::params![id])?;
        let mut out = Vec::new();
        while let Some(r) = rows.next()? {
            out.push((r.get(0)?, r.get(1)?));
        }
        Ok(out)
    }

    pub fn add_metric(&self, id: i64, ts_ms: i64, rss: i64, disk: i64) -> Result<()> {
        self.lock().execute(
            "INSERT INTO metrics (job_id, ts_ms, rss_bytes, disk_bytes) VALUES (?, ?, ?, ?)",
            duckdb::params![id, ts_ms, rss, disk],
        )?;
        Ok(())
    }

    pub fn get_job(&self, id: i64) -> Result<Option<Job>> {
        let c = self.lock();
        let mut stmt = c.prepare(
            "SELECT id, created_ms, started_ms, finished_ms, status, phase, exit_code, ram_peak, disk_peak, reaped_ms, summary, repro_summary, result_summary, detail, source_url, title, short_title, summary_meta
             FROM jobs WHERE id=?",
        )?;
        let mut rows = stmt.query(duckdb::params![id])?;
        if let Some(r) = rows.next()? {
            Ok(Some(row_to_job(r)?))
        } else {
            Ok(None)
        }
    }

    pub fn list_jobs(&self) -> Result<Vec<Job>> {
        let c = self.lock();
        let mut stmt = c.prepare(
            "SELECT id, created_ms, started_ms, finished_ms, status, phase, exit_code, ram_peak, disk_peak, reaped_ms, summary, repro_summary, result_summary, detail, source_url, title, short_title, summary_meta
             FROM jobs ORDER BY id DESC",
        )?;
        let mut rows = stmt.query([])?;
        let mut out = Vec::new();
        while let Some(r) = rows.next()? {
            out.push(row_to_job(r)?);
        }
        Ok(out)
    }

    pub fn metrics(&self, id: i64) -> Result<Vec<Sample>> {
        let c = self.lock();
        let mut stmt = c.prepare(
            "SELECT ts_ms, rss_bytes, disk_bytes FROM metrics WHERE job_id=? ORDER BY ts_ms",
        )?;
        let mut rows = stmt.query(duckdb::params![id])?;
        let mut out = Vec::new();
        while let Some(r) = rows.next()? {
            out.push(Sample { ts_ms: r.get(0)?, rss_bytes: r.get(1)?, disk_bytes: r.get(2)? });
        }
        Ok(out)
    }

    pub fn peaks(&self) -> Result<Vec<Peak>> {
        let c = self.lock();
        let mut stmt = c.prepare(
            "SELECT id, ram_peak, disk_peak, status FROM jobs ORDER BY id DESC",
        )?;
        let mut rows = stmt.query([])?;
        let mut out = Vec::new();
        while let Some(r) = rows.next()? {
            out.push(Peak { id: r.get(0)?, ram_peak: r.get(1)?, disk_peak: r.get(2)?, status: r.get(3)? });
        }
        Ok(out)
    }

    /// Mark any jobs left mid-flight by a previous run as failed (startup recovery).
    pub fn recover_orphans(&self, now_ms: i64) -> Result<()> {
        self.lock().execute(
            "UPDATE jobs SET status='failed', finished_ms=? WHERE status IN ('queued','running')",
            duckdb::params![now_ms],
        )?;
        Ok(())
    }

    /// Finished jobs older than `before_ms` whose on-disk dir hasn't been reaped yet.
    pub fn reapable(&self, before_ms: i64) -> Result<Vec<i64>> {
        let c = self.lock();
        let mut stmt = c.prepare(
            "SELECT id FROM jobs WHERE finished_ms IS NOT NULL AND finished_ms < ? AND reaped_ms IS NULL ORDER BY id",
        )?;
        let mut rows = stmt.query(duckdb::params![before_ms])?;
        let mut out = Vec::new();
        while let Some(r) = rows.next()? {
            out.push(r.get(0)?);
        }
        Ok(out)
    }

    /// Record that a job's on-disk dir (logs included) was removed by the sweep.
    pub fn mark_reaped(&self, id: i64, ts_ms: i64) -> Result<()> {
        self.lock()
            .execute("UPDATE jobs SET reaped_ms=? WHERE id=?", duckdb::params![ts_ms, id])?;
        Ok(())
    }

    // --- LKML monitor: seen-set + candidates ---------------------------------
    // The auto-poll monitor was dropped in favor of on-demand browse, so the write
    // side (seen-set + add_candidate) is currently unused; kept so the monitor can be
    // re-enabled without re-deriving the schema. The read side (list_candidates /
    // get_candidate_bundle) still backs the dormant "From LKML" panel + Run endpoint.
    #[allow(dead_code)]
    /// True if the monitor has already evaluated this message id (any prior poll).
    pub fn lkml_seen(&self, msgid: &str) -> Result<bool> {
        let c = self.lock();
        let n: i64 = c.query_row(
            "SELECT count(*) FROM lkml_seen WHERE msgid=?",
            duckdb::params![msgid], |r| r.get(0))?;
        Ok(n > 0)
    }

    #[allow(dead_code)]
    /// Mark a message id as evaluated so it is never re-fetched. Idempotent.
    pub fn lkml_mark_seen(&self, msgid: &str, list: &str, now_ms: i64) -> Result<()> {
        self.lock().execute(
            "INSERT INTO lkml_seen (msgid, list, seen_ms) VALUES (?, ?, ?)
             ON CONFLICT (msgid) DO NOTHING",
            duckdb::params![msgid, list, now_ms],
        )?;
        Ok(())
    }

    #[allow(dead_code)]
    /// Record a qualifying cover letter as a runnable candidate. Idempotent on msgid.
    pub fn add_candidate(&self, msgid: &str, list: &str, title: &str,
                         source_url: &str, bundle: &str, now_ms: i64) -> Result<()> {
        self.lock().execute(
            "INSERT INTO candidates (msgid, list, title, source_url, bundle, detected_ms)
             VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT (msgid) DO NOTHING",
            duckdb::params![msgid, list, title, source_url, bundle, now_ms],
        )?;
        Ok(())
    }

    /// Candidates for the site, newest first (without the bundle text).
    pub fn list_candidates(&self) -> Result<Vec<Candidate>> {
        let c = self.lock();
        let mut stmt = c.prepare(
            "SELECT msgid, list, title, source_url, detected_ms, job_id
             FROM candidates ORDER BY detected_ms DESC",
        )?;
        let mut rows = stmt.query([])?;
        let mut out = Vec::new();
        while let Some(r) = rows.next()? {
            out.push(Candidate {
                msgid: r.get(0)?, list: r.get(1)?, title: r.get(2)?,
                source_url: r.get(3)?, detected_ms: r.get(4)?, job_id: r.get(5)?,
            });
        }
        Ok(out)
    }

    /// The stored bundle text + (source_url, title) for a candidate, or None.
    pub fn get_candidate_bundle(&self, msgid: &str) -> Result<Option<(String, String, Option<String>)>> {
        let c = self.lock();
        let mut stmt = c.prepare(
            "SELECT bundle, source_url, title FROM candidates WHERE msgid=?",
        )?;
        let mut rows = stmt.query(duckdb::params![msgid])?;
        if let Some(r) = rows.next()? {
            Ok(Some((r.get(0)?, r.get(1)?, r.get(2)?)))
        } else {
            Ok(None)
        }
    }

    /// Link a candidate to the job created from it (after Run).
    pub fn set_candidate_job(&self, msgid: &str, job_id: i64) -> Result<()> {
        self.lock().execute(
            "UPDATE candidates SET job_id=? WHERE msgid=?",
            duckdb::params![job_id, msgid],
        )?;
        Ok(())
    }
}

fn row_to_job(r: &duckdb::Row<'_>) -> Result<Job> {
    Ok(Job {
        id: r.get(0)?,
        created_ms: r.get(1)?,
        started_ms: r.get(2)?,
        finished_ms: r.get(3)?,
        status: r.get(4)?,
        phase: r.get(5)?,
        exit_code: r.get(6)?,
        ram_peak: r.get(7)?,
        disk_peak: r.get(8)?,
        reaped_ms: r.get(9)?,
        summary: r.get(10)?,
        repro_summary: r.get(11)?,
        result_summary: r.get(12)?,
        detail: r.get(13)?,
        source_url: r.get(14)?,
        title: r.get(15)?,
        short_title: r.get(16)?,
        summary_meta: r.get(17)?,
    })
}
